name: Periodic build

# "Every 48 hours", try to compile the mod.
# This is because it currently compiles against Botania HEAD and that might change from under me.
# Sidenote; this isn't actually "every 48 hours" because cron syntax for that literally does not exist!
# It's on "even-numbered days of the month". Isnt it crazy how the de-facto standard for scheduling events
# does not allow you to actually run an event once every 48 hours. Also yes it builds at 06:09am

on:
  schedule:
    - cron: "9 6 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle™
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

#      - name: Upload artifacts™
#        uses: actions/upload-artifact@v2
#        with:
#          name: Artifacts
#          path: |
#            Fabric/build/libs/
#            Forge/build/libs/